swagger: "2.0"
info:
  title: Crossfit Agenda
  version: 1.0.0
host: localhost:8080
basePath: /v1
schemes:
  - http
paths:
  /start:
    post:
      summary: Start process to fill our calendar
      operationId: startCrossfitAgenda
      produces:
        - application/json
      responses:
        202:
          $ref: '#/definitions/Agenda'
        500:
          $ref: '#/definitions/Error'
  /status:
    get:
      summary: Status process
      operationId: status
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Status'

securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Status:
    type: object
    properties:
      id:
        type: integer
        format: int64
      date:
        type: integer
        format: uint64
      detail:
        type: string
      status:
        type: string
        description: Process Status
        enum:
          - working
          - finished
          - failed
      complete:
        type: boolean
        default: false
    required:
      - id
      - date
      - detail
      - status
      - complete
  Agenda:
    type: object
    properties:
      id:
        type: integer
        format: int64
    required:
      - id
  Error:
    type: object
    properties:
      status:
        type: number
      message:
        type: string
      date:
        type: string
    required:
      - status
      - message
      - date